{
 "title": "Simple Cluster Dashboard",
 "description": "Simple Cluster Dashboard (13043)",
 "tags": [
  "prometheus",
  "k3s",
  "raspberry"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "HOST", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{mode=\"idle\"}) without (cpu,mode))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Node Load 5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load5{node=~\"[[HOST]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Used Filesystem",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/storage\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/storage\",fstype!=\"rootfs\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(node_network_up) by (node)", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Node Temp",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_thermal_zone_temp) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_http_requests_duration_seconds_sum{kubernetes_io_hostname=~\"[[HOST]]\"}[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{k3s_io_hostname}}"
    }
   ]
  },
  {
   "title": "TCP Established Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{node=~\"[[HOST]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Transmit Rate (In/Out)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node=~\"[[HOST]]\"}[5m])) by (node)",
     "legendFormat": "{{node}} IN"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node=~\"[[HOST]]\"}[5m])) by (node)",
     "legendFormat": "{{node}} OUT"
    }
   ]
  }
 ]
}