{
 "title": "Raspberry Pi K3S Cluster - Cronjobs",
 "description": "Raspberry Pi K3S Cluster - Cronjobs (14279)",
 "tags": [
  "prometheus",
  "k3s",
  "raspberry",
  "cronjob"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "cronjob",
    "query": {
     "query": "label_values(kube_cronjob_info{namespace=\"$namespace\"},cronjob)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Cronjobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total number of CronJobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of Suspended CronJobs",
   "type": "stat",
   "description": "Must be equal to Zero",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_spec_suspend{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_status_active{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Failed jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_failed{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Succeeded jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_status_succeeded{namespace=\"$namespace\"}==1)"
    }
   ]
  },
  {
   "title": "CronJobs status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 2 },
   "targets": [
    {
     "expr": "count(kube_job_failed{namespace=\"$namespace\"}==1)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    },
    {
     "expr": "count(kube_job_status_succeeded{namespace=\"$namespace\"}==1)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    }
   ]
  },
  { "title": "Cronjob Details : $cronjob", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "cronjob" },
  {
   "title": "Schedule",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,(kube_cronjob_info{namespace=\"$namespace\",cronjob=\"$cronjob\"}))"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (owner_name)\n(\n  kube_job_status_active{namespace=\"$namespace\"} * on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    }
   ]
  },
  {
   "title": "Maximum Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (owner_name)\n(\n  max by(job_name )\n   (\n     kube_job_status_completion_time{namespace=\"$namespace\"} - on (job_name)\n       kube_job_created{namespace=\"$namespace\"} \n   ) * on (job_name)\n   \n    group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n\n)  \n\n"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (owner_name)\n(\n  max by(job_name )\n   (\n     kube_job_status_completion_time{namespace=\"$namespace\"} - on (job_name)\n       kube_job_created{namespace=\"$namespace\"} \n   ) * on (job_name)\n   \n    group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n\n)  \n\n\n\n"
    }
   ]
  },
  {
   "title": "$cronjob status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum by (owner_name)\n(\n  kube_job_complete{namespace=\"$namespace\"} + on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    },
    {
     "expr": "sum by (owner_name)\n(\n  kube_job_failed{namespace=\"$namespace\"} + on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    }
   ]
  },
  {
   "title": "Next Scheddule",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_cronjob_next_schedule_time{namespace=\"$namespace\",cronjob=\"$cronjob\"}*1000)"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum \n(\n  kube_job_failed{namespace=\"$namespace\"} + on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    }
   ]
  },
  {
   "title": "Minimum Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (\n  (kube_job_status_completion_time{namespace=\"$namespace\"}\n  - on (job_name)\n    kube_job_created{namespace=\"$namespace\"})\n  * on (job_name)\n    group_left(owner_name)\n      (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n)\n\n\n\n"
    }
   ]
  },
  {
   "title": "Last Scheddule",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_cronjob_status_last_schedule_time{namespace=\"$namespace\",cronjob=\"$cronjob\"}*1000"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\n(\n  kube_job_complete{namespace=\"$namespace\"} + on (job_name)\n\n  group_left(owner_name)\n\n  (group by (job_name,owner_name) (kube_job_owner{owner_name=\"$cronjob\"}))\n  \n)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    }
   ]
  }
 ]
}