{
 "title": "Raspberry Pi K3S Cluster - Pi-Hole Dashboard",
 "description": "Raspberry Pi K3S Cluster - Pi-Hole Dashboard",
 "tags": [
  "prometheus",
  "k3s",
  "raspberry",
  "pihole"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(pihole_status,job)"
    }
   },
   {
    "name": "host",
    "label": "Host:",
    "query": {
     "query": "label_values(pihole_status{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "🍓PI-Hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_status{instance=~\"$host\"}",
     "legendFormat": "{{ instance  }}"
    }
   ]
  },
  {
   "title": "Total domains being blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pihole_domains_being_blocked{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pihole_unique_domains{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (domain)(pihole_top_queries{instance=~\"$host\"})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (type)(pihole_reply{instance=~\"$host\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (domain)(pihole_top_ads{instance=~\"$host\"})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_dns_queries_all_types{instance=~\"$host\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Ads blocked (today)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_ads_blocked_today{instance=~\"$host\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pihole_queries_cached{instance=~\"$host\"})",
     "legendFormat": "Total queries cached"
    },
    {
     "expr": "sum(pihole_queries_forwarded{instance=~\"$host\"})",
     "legendFormat": "Total queries forwarded"
    }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (type)(pihole_querytypes{instance=~\"$host\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum by (domain)(pihole_top_queries{instance=~\"$host\"})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (domain)(pihole_top_ads{instance=~\"$host\"})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (destination)(pihole_forward_destinations{instance=~\"$host\"})",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  {
   "title": "Unique clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_unique_clients{instance=~\"$host\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}