{
 "title": "Raspberry Pi K3S Cluster - FRITZ!Box Router Status",
 "description": "Raspberry Pi K3S Cluster - FRITZ!Box Router Status",
 "tags": [
  "influxdb",
  "fritzbox",
  "k3s"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current UP/DOWN",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "DSL Speed" }
   ],
   "targets": [
    {
     "alias": "UP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "sendrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "DOWN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "receiverate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "DOWN netto Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "downstreammax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "DOWN Physical Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "downstreamphysicalmax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "DOWN DSL Sync",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT last(\"NewDownstreamCurrRate\") *1000 FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "downstream_dsl_sync_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UP netto Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT mean(\"sendrate\") FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "upstreammax" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "UP Physical Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT mean(\"sendrate\") FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "upstreamphysicalmax" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "UP DSL Sync",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT last(\"NewUpstreamCurrRate\") *1000 FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "upstream_dsl_sync_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "CRC Errors",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "crc_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Errored Seconds",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT non_negative_derivative(last(\"crc_errors\"), 10s) FROM \"fritzbox\" WHERE $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "errored_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Severely Errored Seconds",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT non_negative_derivative(last(\"crc_errors\"), 10s) FROM \"fritzbox\" WHERE $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "severely_errored_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Update Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "upgrade_available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DSL Link Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "linkuptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "query": "SELECT last(\"value\") FROM \"fritzbox\" WHERE (\"type_instance\" = 'uptime') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "systemuptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Download",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "receiverate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox",
     "select": [
      [
       { "params": [ "sendrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Upload since connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "fritzbox",
     "query": "SELECT \"totalbytessent\" FROM \"fritzbox\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "totalbytessent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Download since connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "fritzbox",
     "query": "SELECT \"totalbytesreceived\" FROM \"fritzbox\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "totalbytesreceived" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last 24h Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"totalbytessent\"))) FROM \"fritzbox\" WHERE $timeFilter  GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "Last 24h Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"totalbytesreceived\"))) FROM \"fritzbox\" WHERE  $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "Current Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "download",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytesreceived\"))) FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ],
     "target": "alias(summarize(nonNegativeDerivative(collectd.squirrel.fritzbox.bytes-totalbytesreceived, 0), '1h', 'sum'), 'download')"
    },
    {
     "alias": "upload",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "fill": "null",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytessent\"))) FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
     ],
     "target": "alias(summarize(nonNegativeDerivative(collectd.squirrel.fritzbox.bytes-totalbytessent,0),'1h','sum'),'upload')"
    }
   ]
  },
  {
   "title": "Daily Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytesreceived\"))) FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(totalbytessent))) FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "FritzBox Info",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "limit": "1",
     "measurement": "fritzbox",
     "query": "SELECT \"model\" AS \"Model\", \"serialnumber\" AS \"Serial\", \"softwareversion\" AS \"SW Version\", \"external_ip\" AS \"IP\", \"external_ipv6\" AS \"IPv6\", \"number_of_hosts\" AS \"Number of network hosts\", \"connection_status\" AS \"PPP Connection Status\", \"physicallinkstatus\" AS \"Link Status\", \"physicallinktype\" AS \"Link Type\", \"remote_pop\" AS \"Remote POP\", \"last_connection_error\" AS \"Last Connect Error\" FROM \"fritzbox\" WHERE $timeFilter LIMIT 1",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "serialnumber" ], "type": "field" },
       { "params": [ "Serial" ], "type": "alias" }
      ],
      [
       { "params": [ "softwareversion" ], "type": "field" },
       { "params": [ "SW Version" ], "type": "alias" }
      ],
      [
       { "params": [ "external_ip" ], "type": "field" },
       { "params": [ "IP" ], "type": "alias" }
      ],
      [
       { "params": [ "number_of_hosts" ], "type": "field" },
       { "params": [ "Number of network hosts" ], "type": "alias" }
      ],
      [
       { "params": [ "connection_status" ], "type": "field" },
       { "params": [ "PPP Connection Status" ], "type": "alias" }
      ],
      [
       { "params": [ "physicallinkstatus" ], "type": "field" },
       { "params": [ "Link Status" ], "type": "alias" }
      ],
      [
       { "params": [ "physicallinktype" ], "type": "field" },
       { "params": [ "Link Type" ], "type": "alias" }
      ],
      [
       { "params": [ "remote_pop" ], "type": "field" },
       { "params": [ "Remote POP" ], "type": "alias" }
      ],
      [
       { "params": [ "last_connection_error" ], "type": "field" },
       { "params": [ "Last Connect Error" ], "type": "alias" }
      ],
      [
       { "params": [ "external_ipv6" ], "type": "field" },
       { "params": [ "IPv6" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Traffic",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytesreceived\"))) FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytessent\"))) FROM \"fritzbox\" WHERE $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time(1d) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  }
 ]
}